# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-proteomicstmt-1.0dev
channels:
  - openms
  - conda-forge
  - bioconda
dependencies:
#  - openms::openms=2.7.0pre
  - openms::openms-thirdparty=2.7.0pre
  - bioconda::bioconductor-msstats=3.20.1 # will include R
  - bioconda::sdrf-pipelines=0.0.18 # for SDRF conversion
  - bioconda::pmultiqc=0.0.8 # for proteomics plugin of multiqc
  - conda-forge::r-ptxqc=1.0.5 # for QC reports
  - conda-forge::xorg-libxt=1.2.0 # until this R fix is merged: https://github.com/conda-forge/r-base-feedstock/pull/128
  - conda-forge::fonts-conda-ecosystem=1 # for the fonts in QC reports
  - conda-forge::python=3.8.5
  - conda-forge::markdown=3.2.2
  - conda-forge::pymdown-extensions=8.0.1
  - conda-forge::pygments=2.7.1
